server:
    port: ${PORT:8082}

spring:
    jpa:
        defer-datasource-initialization: true
    mustache:
        check-template-location: false

vaadin:
    launch-browser: true
    whitelisted-packages: com.vaadin,org.vaadin,dev.hilla

# Slf4j Levels: error, warn, info, debug, trace
logging:
    level:
        org:
            atmosphere: warn
        com:
            vaadin:
                flux:
                    ui:
                        dragdrop: trace
